### PR TITLE
Fix assertion error during verify and make DCE work with tuples

### LINKED ISSUE #1856: Reduce verify fails with Debug builds for FP16 models
It fails on assertion during `replace_instruction`. 

Steps to reproduce `./driver verify --onnx resnet50.onnx --fp16 --reduce` .

### PR DESCRIPTION
**Pull request by umangyadav**
Fixes #1856 and additionally makes DCE work for Tuple Types

`verify` was failing with `reduce` in debug builds here : 
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/a0fa3742f92239fb60c58d4b73f458efb08ef0ed/src/module.cpp#L349

Assertion was failing because of the following pattern:
`ins --> convert(original_type) --> module_end`. 

And then, it was replacing `ins` with `convert(original_type)` here. https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/a0fa3742f92239fb60c58d4b73f458efb08ef0ed/src/quantize_fp16.cpp#L60

`convert(original_type)` would have no outputs while `ins` would have one output and therefore it would fail assertion here : 
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/blob/a0fa3742f92239fb60c58d4b73f458efb08ef0ed/src/module.cpp#L349

### CODE REVIEW

File: test/dead_code_elimination_test.cpp [hunk 1]
```diff
@@ -274,4 +273,59 @@ TEST_CASE(param_not_eliminated)
...
+        auto r1  = mm->add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 1}}), ret);
+        auto r16 = mm->add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 2}}), ret);
+        mm->add_return({r0, r1, r16});
+
+        return p;
+    };
+    auto p = create_program(true);
+    run_pass(p);
+    EXPECT(p == create_program(false));
+}
```
Comment (pfultz2) [inline test/dead_code_elimination_test.cpp:329]: It seems it would be simpler to add a `tuple_op` under basic_ops.hpp header to create a tuple to test with:

```cpp
struct tuple_op
{
    std::string name() const { return "tuple_op"; }
    migraphx::shape compute_shape(std::vector<migraphx::shape> inputs) const
    {
        return {inputs};
    }
};

TEST_CASE(tuple_test)
{
    migraphx::program p;
    auto* mm = p.get_main_module();
    auto one = mm->add_literal(1);
    auto two = mm->add_literal(2);
    mm->add_instruction(tuple_op{}, one, two);
    mm->add_return({one, two});
    auto count = std::distance(mm->begin(), mm->end());
    run_pass(p);
    EXPECT(std::distance(mm->begin(), mm->end()) == (count - 1));
}
```

Comment (umangyadav) [reply test/dead_code_elimination_test.cpp:287]: Done.

File: test/include/basic_ops.hpp [hunk 2]
```diff
@@ -186,6 +186,18 @@ struct nop
     migraphx::shape compute_shape(const std::vector<migraphx::shape>&) const { return {}; }
 };
 
+struct tuple_op
+{
+    std::string name() const { return "tuple_op"; }
+    migraphx::shape compute_shape(std::vector<migraphx::shape> inputs) const { return {inputs}; }
```
[the remark this answers is not in the document]
Comment (umangyadav) [reply test/include/basic_ops.hpp]: Done.

File: src/dead_code_elimination.cpp [hunk 3]
```diff
@@ -50,7 +50,9 @@ void dead_code_elimination::apply(module& m) const
             break;
         // Skip instruction with empty shape as output unless its [dynamic, builtin, undefined,
         // identity, allocate]
```
Comment (kahmed10) [inline src/dead_code_elimination.cpp:52]: I think this comment should be updated as well

Comment (umangyadav) [reply src/dead_code_elimination.cpp]: Done.

**Review by CharlieL7 — APPROVED** [review]

**Review by TedThemistokleous — APPROVED** [review]

**Review by kahmed10 — APPROVED** [review]
